#ifndef EVENTS_H
#define EVENTS_H

#define UPDATE_TEMP_EVENT "UPDATE_TEMP"
#define GET_TEMP_EVENT "GET_TEMP_EVENT"
#define SENSOR_CHANGE "SENSOR_CHANGE"
#define SERVER_CLOSED "SERVER_CLOSED"
#define GPIO_DEVICE_STATE "GPIO_DEVICE_STATE"
#define CHANGE_SENSOR_VALUE "CHANGE_SENSOR_VALUE"
#define ALL_SENSORS_STATES "ALL_SENSORS_STATES"

#endif /* EVENTS_H */